### ISSUE TITLE
Low percentages mapped and unmapped

### ISSUE THREAD

**Issue by larouchej** [Hoohm/CITE-seq-Count#82] opened 2019-09-26 12:52 UTC
Hello,
I have been trying to use CITE-seq-count to demultiplex pooled 10X samples (up to 4 TSA HTOs per sample), but it is returning only 12% mapped and 6% unmapped using the command:

CITE-seq-Count -R1 GEX_matrix.fastq.gz -R2 HTO_matrix.fastq.gz -t TAG_LIST.csv -cbf 1 -cbl 16 -umif 17 -umil 26 -cells 3231 -o outfolder

I tried running the first 100, 500 and 5000 lines using the -n command and got around 66% aligned for -n 5000. I also tried --debug for -n 100 to verify that no trimming was needed before mapping. In case, I also tried adding --sliding-window True for the entire dataset to be sure that no trimming was needed later in the fastq file.

Do you know what could be happening?

Thanks.

**Comment by Hoohm** [comment] 2019-09-27 11:51
Hello @larouchej 
I would use the option `-u UNMAPPED_FILE, --unmapped-tags UNMAPPED_FILE` to check what is in there. Might help figuring out what the issue is with your data.

Let me know if it's enough.

**Comment by larouchej** [comment] 2019-10-02 11:46
Hi @Hoohm 
Thanks for your suggestion! I generated the csv of unmapped reads and, I suppose not surprisingly, they are not similar and do not contain the HTO reads (the majority of unmapped reads were sequences of all G's). I'm guessing this means there was an error with the experiment prep/sequencing? Have you had this before or know what could have gone wrong?
Thanks again.

**Comment by Hoohm** [comment] 2019-10-07 08:15
Hello @larouchej,
I don't know sorry as I didn't encounter those issues.
Something went wrong in the prep. Maybe the tags aren't being captured properly or they did not stick to the cells. I really can't tell, sorry.

If you figure it out, please let me know, I can add it to the documentation to help other people with a similar issue.

**Comment by Hoohm** [comment] 2019-12-02 16:36
Closing this for now. Feel free to reopen if you have updates regarding this issue.

**Closed by Hoohm** 2019-12-02 16:36 UTC
